- docs/unraid-os/release-notes/6.10.1.md
- docs/unraid-os/release-notes/6.10.3.md
- docs/unraid-os/release-notes/6.11.0.md
- docs/unraid-os/release-notes/6.11.1.md
- docs/unraid-os/release-notes/6.11.2.md
- docs/unraid-os/release-notes/6.11.3.md
- docs/unraid-os/release-notes/6.11.4.md
- docs/unraid-os/release-notes/6.11.5.md
- docs/unraid-os/release-notes/6.9.0.md
- docs/unraid-os/release-notes/6.9.2.md
> add more release notes

- docs/legacy/Manual/Multi-language.md
> fix image placement

- .vscode/extensions.json
> add markdownlint recommended extension for vscode

- .github/workflows/pr.yml
- docusaurus.config.js
> feat: new languages in docusaurus

- docs/unraid-os/manual/getting-started.md
- docusaurus.config.js
> When building, warn on broken links

- docs/connect/remote-access.md
- docs/legacy/_category_.json
- docs/unraid-os/manual/getting-started.md
- docusaurus.config.js
- i18n/zh/docusaurus-plugin-content-docs/current/legacy/Articles/Getting_Started.md
> Link to Legacy Wiki

- docs/unraid-os/manual/storage-management.md
4. [x] Is the build succeeding?
> Improve formatting of the Storage Management page

- docs/unraid-os/manual/storage-management.md
4. [x] Is the build succeeding?
> Fix outdated link in storage-management.md

- docs/unraid-os/release-notes/6.12.0.md
> Update 6.12.0 release notes

- docs/unraid-os/release-notes/6.12.0.md
> additional editing

- docs/unraid-os/release-notes/6.12.0.md
Fixed a few misspellings and cleaned up the formatting for consistency
> Update 6.12.0.md - Typos and formatting

- docs/unraid-os/manual/storage-management.md
Fix extra spaces and typo.
4. [x] Is the build succeeding?
> Update storage-management.md - Extra spaces and typo

- docs/unraid-os/release-notes/6.12.1.md
> 6.12.1 release notes

- docs/unraid-os/release-notes/6.12.1.md
> Update 6.12.1 release notes

- docs/unraid-os/manual/upgrade-instructions.md
> Add manual upgrade instructions

- docs/unraid-os/manual/troubleshooting.md
> Update command line diagnostics info

- docs/unraid-os/manual/additional-settings.md
- docs/unraid-os/manual/applications.md
- docs/unraid-os/manual/changing-the-flash-device.md
- docs/unraid-os/manual/docker-management.md
- docs/unraid-os/manual/getting-started.md
- docs/unraid-os/manual/security.md
- docs/unraid-os/manual/shares.md
- docs/unraid-os/manual/storage-management.md
- docs/unraid-os/manual/tools.md
- docs/unraid-os/manual/troubleshooting.md
- docs/unraid-os/manual/users.md
- docs/unraid-os/manual/vm-management.md
- docs/unraid-os/manual/vm-support.md
Just a new Unraid user, reading through the manual for the first time. Saw some spelling/formatting mistakes.
4. [x] Is the build succeeding?
> manual cleanup

- docs/unraid-os/manual/changing-the-flash-device.md
- docs/unraid-os/manual/getting-started/_category_.json
- docs/unraid-os/manual/getting-started/getting-started.md
- docs/unraid-os/manual/getting-started/manual-install-method.md
- i18n/es/docusaurus-plugin-content-docs/current/unraid-os/manual/getting-started/manual-install-method.md
- i18n/zh/docusaurus-plugin-content-docs/current/unraid-os/manual/x-getting-started.md
> feat: getting started localization

- docs/unraid-os/release-notes/6.12.3.md
> Unraid OS 6.12.3 release notes

- docusaurus.config.js
- package-lock.json
- package.json
1. [x] Are internal links to wiki documents using [relative file links](https://docusaurus.io/docs/markdown-features/links)?
2. [x] Are all new documentation files lowercase, with dash separated names (ex. unraid-os.mdx)?
3. [x] Are all assets (images, etc), located in an assets/ subfolder next to the .md/mdx files?
5. [x] Is the build succeeding?
> Add redirect plugin

- docs/connect/remote-access.md
- docs/unraid-os/manual/additional-settings.md
- docs/unraid-os/manual/getting-started/getting-started.md
- docs/unraid-os/release-notes/6.10.0.md
1. [x] Are internal links to wiki documents using [relative file links](https://docusaurus.io/docs/markdown-features/links)?
2. [x] Are all new documentation files lowercase, with dash separated names (ex. unraid-os.mdx)?
3. [x] Are all assets (images, etc), located in an assets/ subfolder next to the .md/mdx files?
5. [x] Is the build succeeding?
> Fix broken links

- docs/unraid-os/release-notes/6.12.4.md
> clarify 6.12.4 release notes

- docs/unraid-os/release-notes/6.12.5.md
> Add 6.12.5 release notes

- docs/unraid-os/release-notes/6.12.6.md
> Add 6.12.6 release notes

- docs/unraid-os/release-notes/6.12.0.md
- docs/unraid-os/release-notes/6.12.6.md
> Update known issues in 6.12.6

- docs/unraid-os/download_list.mdx
- src/components/ReleasesList/index.tsx
> feat: download urls on docs

- docs/unraid-os/getting-started/getting-started.md
1. [ x] Are internal links to wiki documents using [relative file links](https://docusaurus.io/docs/markdown-features/links)?
2. [ x] Are all new documentation files lowercase, with dash separated names (ex. unraid-os.mdx)?
3. [ x] Are all assets (images, etc), located in an assets/ subfolder next to the .md/mdx files?
4. [ x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
> Add hardware requirements

- docs/unraid-os/release-notes/6.12.7.md
> Add 6.12.7 release notes

- docs/unraid-os/faq/unraid-account.md
> refactor: faq unraid account additions 

- src/components/ReleasesList/index.tsx
> feat: split URL categories to featured / archive

- docs/unraid-os/getting-started/manual-install-method.md
- docs/unraid-os/manual/upgrade-instructions.md
> download from new archive

- docs/unraid-os/manual/zfs/placeholder.md
Copied ZFS pool info from release notes of 6.12.0 to ZFS section in the manual. It's much easier to find under the heading ZFS. A noob wont know to look in 6.12.0 release notes.
Further updates to come.
1. [x] Are internal links to wiki documents using [relative file links](https://docusaurus.io/docs/markdown-features/links)?
2. [x] Are all new documentation files lowercase, with dash separated names (ex. unraid-os.mdx)?
3. [x] Are all assets (images, etc), located in an assets/ subfolder next to the .md/mdx files?
5. [x] Is the build succeeding?
> zfs-update-placeholder.md

- docs/unraid-os/faq/installation.md
- docs/unraid-os/getting-started/getting-started.md
- docs/unraid-os/getting-started/manual-install-method.md
- docs/unraid-os/manual/changing-the-flash-device.md
> Remove 32 GB limit for flash drives

- docs/unraid-os/release-notes/6.12.9.md
> Add 6.12.9 release notes

- docs/unraid-os/faq/licensing-faq.md
- docs/unraid-os/manual/storage-management.md
> Cleanup formatting

- docs/unraid-os/release-notes/6.12.10.md
> Add 6.12.10 release notes

- docs/connect/help.md
- docs/connect/remote-access.md
- docs/legacy/Articles/upgrading-to-unraid-6.md
- docs/legacy/FAQ/check-disk-filesystems.md
- docs/legacy/FAQ/parity-swap-procedure.md
- docs/legacy/FAQ/replacing-a-data-drive.md
- docs/legacy/FAQ/shrink-array.md
- docs/legacy/FAQ/terminal-access.md
- docs/legacy/FAQ/usb-flash-drive-preparation.md
- docs/unraid-os/faq/installation.md
- docs/unraid-os/faq/licensing-faq.md
- docs/unraid-os/faq/os-faq.md
- docs/unraid-os/faq/redeem-license-activation-code.md
- docs/unraid-os/guides/configuring-time-machine.md
- docs/unraid-os/manual/docker-management.md
- docs/unraid-os/manual/multi-language.md
- docs/unraid-os/manual/storage-management.md
- docs/unraid-os/manual/troubleshooting.md
- docs/unraid-os/manual/upgrade-instructions.md
- docs/unraid-os/manual/vm-support.md
- docs/unraid-os/release-notes/6.10.0.md
- docs/unraid-os/release-notes/6.10.2.md
- docs/unraid-os/release-notes/6.9.0.md
Changelog:
- Fix the link for "transfer your" in https://docs.unraid.net/unraid-os/faq/licensing-faq/#what-happens-if-my-usb-fails-do-i-have-to-repurchase-a-license
- Use "→" instead of "\>" and "-\>"
- Improve readability
> Minor fixes and improvements

- docs/legacy/Articles/upgrading-to-unraid-6.md
- docs/unraid-os/manual/upgrade-instructions.md
> Update manual upgrade URL

- docs/unraid-os/release-notes/7.0.0.md
> Add 7.0.0-beta.1 release notes

- docs/unraid-os/release-notes/7.0.0.md
> Add 7.0.0-beta.2 release notes

- docs/unraid-os/release-notes/7.0.0.md
> Avoid using Docker directory on ZFS pool

- docs/unraid-os/release-notes/6.12.11.md
> Add 6.12.11 Release Notes

- docusaurus.config.js
> Add go links for the OS

- docusaurus.config.js
> Add go links for Forum Word Expansion

- docusaurus.config.js
> Add go links for website

- docusaurus.config.js
> Add more go links

- docs/contribute-to-docs/redirect_list.mdx
- src/components/RedirectList/index.tsx
> Add dynamic page to show redirects

- docs/unraid-os/release-notes/6.12.12.md
> Add 6.12.12 Release Notes

- docusaurus.config.js
1. [X] Are internal links to wiki documents using [relative file links](https://docusaurus.io/docs/markdown-features/links)?
2. [X] Are all new documentation files lowercase, with dash separated names (ex. unraid-os.mdx)?
3. [X] Are all assets (images, etc), located in an assets/ subfolder next to the .md/mdx files?
4. [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
5. [X] Is the build succeeding?
> fix: add go redirect for 6.12.12 & 6.12.13 release notes

- docs/unraid-os/manual/security/tailscale.md
- docusaurus.config.js
> Add Tailscale docs

- docs/unraid-os/release-notes/7.1.0.md
> Add 7.1.0-beta.2 release notes

- docs/unraid-os/release-notes/7.1.0.md
- docs/unraid-os/release-notes/7.1.1.md
> Add warning for mover

- docs/unraid-os/release-notes/7.2.0.md
> Update 7.2.0-beta.1 release notes
